### ISSUE TITLE
Member Registration: Waiver, Guidelines, Volunteer

### ISSUE THREAD

**Issue by FeXd** [BridgeCityBicycleCoop/workstand-shop-app#86]
I was pointed to the current paper member agreeement form that is used physically when workstand is not available.

https://docs.google.com/document/d/1rf_yotD62Y2Z7cLpXl_ZdQysocjsz5pfNRlTE07GIKg/edit

It highlights two missing things.

- ability to flag if member is interested in volunteering (important for future followups, adding to mailing lists, etc.)
- Member Rights and Respect Guidelines which users have to accept

As discussed, a possible solution for the guidelines would be to add them below the current Waiver, and make both those sections some form of accordion to save space. 

Note that the waiver and guideilens are posted physically in the shop as well.

**Comment by mikemitchel** [comment]
waiver and guidelines are added with accordion
